FROM python:3.9-slim

WORKDIR /app

# Instalamos Flask directamente para mantenerlo simple
RUN pip install flask

COPY app.py .

# El puerto que definimos en el código Python
EXPOSE 5000

CMD ["python", "app.py"]