apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  [cite_start]namespace: dev # Especificamos que este servicio vive en el ambiente dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: ivannduumi/service-a:v1.5-dev # Ruta de tu imagen en Docker Hub
        ports:
        - containerPort: 80