apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: ivannduumi/service-b:v1.5-dev
        ports:
        - containerPort: 5000